### ISSUE TITLE
Version mix up?

### ISSUE THREAD

**Issue by groenmarsmannetje** [aex351/home-assistant-neerslag-card#18]
HACS reports that there is a new version, but that seems to be an older version according to version number.

"U gebruikt versie 2021.04.12.0 , versie 2021.02.27.2 is beschikbaar"

Doesn't look correct. I will not update.

**Comment by alexvdleek** [comment]
Same problem here with version 2021.04.12.0  to 2021.02.27.2. in HACS

**Comment by aex351** [comment]
I changed (corrected) the names/version of earlier releases. Version 2021.27.02.1 is now 2021.02.27.1 for example. In the format year.month.day.release.

This is so that in dropdown boxes the order of releases is now correct. 2021.04.12.0 is a higher number.

For me in HACS when instelling the Neerslag Card the order is correct. However based on there report it seems for the updating mechanisme it is using the latest release of Github, instead of the version number.

I will make another release based on 2012.04.12.0
